name: healthsaathi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase & Firestore
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  firebase_storage: ^11.6.6

  # Video Call
  agora_rtc_engine: ^6.3.0

  # Device Access
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.1

  # OCR
  google_ml_kit: ^0.20.0
  google_mlkit_text_recognition: ^0.15.0

  # Notifications & Localizations
  flutter_local_notifications: ^19.2.1
  flutter_localizations:
    sdk: flutter

  # UI & Utils
  intl: ^0.19.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  timezone: ^0.10.1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/images/signup.jpg
    - lib/assets/images/healthsaathi2.jpg
    - lib/assets/images/doctor.jpg
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: s.dart
  output-class: S


