// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_tT5PiiCStTrWCk2_PFKUK7P196MR6s',
    appId: '1:439068515145:web:7f199fb991801e038a1898',
    messagingSenderId: '439068515145',
    projectId: 'healthsaathi-b09f9',
    authDomain: 'healthsaathi-b09f9.firebaseapp.com',
    storageBucket: 'healthsaathi-b09f9.firebasestorage.app',
    measurementId: 'G-RLB8320E42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Myq0Fm7x5Sq2UiHXAw5oEemr3E4MLJo',
    appId: '1:439068515145:android:45ce45e6a501b58a8a1898',
    messagingSenderId: '439068515145',
    projectId: 'healthsaathi-b09f9',
    storageBucket: 'healthsaathi-b09f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2C_kKBObZbtgh4Go3mZtyDl9Ea-a-GvA',
    appId: '1:439068515145:ios:58530c4e4a8cce828a1898',
    messagingSenderId: '439068515145',
    projectId: 'healthsaathi-b09f9',
    storageBucket: 'healthsaathi-b09f9.firebasestorage.app',
    iosBundleId: 'com.example.healthsaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2C_kKBObZbtgh4Go3mZtyDl9Ea-a-GvA',
    appId: '1:439068515145:ios:58530c4e4a8cce828a1898',
    messagingSenderId: '439068515145',
    projectId: 'healthsaathi-b09f9',
    storageBucket: 'healthsaathi-b09f9.firebasestorage.app',
    iosBundleId: 'com.example.healthsaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6_tT5PiiCStTrWCk2_PFKUK7P196MR6s',
    appId: '1:439068515145:web:4a998f45b3b3ae3c8a1898',
    messagingSenderId: '439068515145',
    projectId: 'healthsaathi-b09f9',
    authDomain: 'healthsaathi-b09f9.firebaseapp.com',
    storageBucket: 'healthsaathi-b09f9.firebasestorage.app',
    measurementId: 'G-4W333D9WKQ',
  );
}
